---

- name: install dependencies
  apt:
    state: latest
    update_cache: yes
    install_recommends: no
    name:
      - curl

- name: get url of latest text.management editor release
  shell: curl -s https://api.github.com/repos/mindofmatthew/text.management/releases | grep browser_ | grep \.deb | cut -d\" -f4 | sort -V | tail -n 1
  args:
    warn: false
  register: tmver
  changed_when: false

- name: download latest text.management editor deb package
  get_url:
    url: "{{ tmver.stdout | trim }}"
    dest: /tmp/text.management.deb
